<?php

namespace app\controllers;

use yii\rest\ActiveController;

class ApiComputadorController extends ActiveController
{
    public $modelClass = 'app\models\PortalComputador';

    public function actions()
    {
        return parent::actions(); // TODO: Change the autogenerated stub
    }
}
